### ISSUE TITLE
Add check

### ISSUE THREAD

**Issue by FrankXie05** [xiaozhuai/vcpkg_demo#1]
Added check code:
```
inline sk_sp<SkImage> loadSkImageFromFile(const std::string &file) {
    auto data = SkData::MakeFromFileName(file.c_str());
    if (!data) {
        // if none
        return nullptr;
    }

    // print the size for  checking 
    printf("File size: %zu, Data size: %zu\n", getFileSize(file), data->size());

    if (data->size() != getFileSize(file)) {
        // return nullptr to debug 
        return nullptr;
    }

    return SkImages::DeferredFromEncodedData(data);
}
```

https://github.com/xiaozhuai/vcpkg_demo/blob/efc843ed8b06d93a7164ff1292d33e8042b34906/src/skia/src/main.cpp#L53

**Comment by FrankXie05** [comment]
@xiaozhuai

**Comment by FrankXie05** [comment]
Can I use Chinese? :)

**Comment by xiaozhuai** [comment]
> Can I use Chinese? :)
@FrankXie05 那可太舒服了~

**Comment by xiaozhuai** [comment]
我调试了一下，这里的data不是nullptr，size是一个很大的值，非常奇怪。这个问题是近期的vcpkg PR引入的。

**Comment by FrankXie05** [comment]
问题:SIGBUS指向的是内存地址的不正确， 有可能是因为加载函数的生命周期没有释放？

**Comment by FrankXie05** [comment]
或者使用C++的方法来加载：
```

inline sk_sp<SkImage> loadSkImageFromFile(const std::string &file) {
    // 使用文件流读取整个文件内容
    std::ifstream fileStream(file, std::ios::binary | std::ios::ate);
    if (!fileStream.is_open()) {
        // 处理文件无法打开的情况
        return nullptr;
    }

    std::streamsize fileSize = fileStream.tellg();
    fileStream.seekg(0, std::ios::beg);

    std::vector<char> fileData(fileSize);
    if (!fileStream.read(fileData.data(), fileSize)) {
        // 处理文件读取失败的情况
        return nullptr;
    }

    // 创建 SkData 对象
    auto data = SkData::MakeWithoutCopy(fileData.data(), fileSize);
    if (!data) {
        // 处理 SkData 创建失败的情况
        return nullptr;
    }

    return SkImages::DeferredFromEncodedData(data);
}
```

**Comment by xiaozhuai** [comment]
> 或者使用C++的方法来加载：

我尝试一下。顺便麻烦看一下下面的commit，这是在vcpkg的skia更新版本后做的修改

https://github.com/xiaozhuai/vcpkg_demo/commit/efc843ed8b06d93a7164ff1292d33e8042b34906

----

使用std::fstream也是同样的错误。
读取文件没有问题，还是崩在`SkImages::DeferredFromEncodedData(data);`这一行

**Comment by xiaozhuai** [comment]
@FrankXie05 你可以复现这个问题吗？

**Comment by AppleJ01** [comment]
@xiaozhuai 抱歉，我跟前没有机器来复现.

**Comment by AppleJ01** [comment]
>读取文件没有问题，还是崩在SkImages::DeferredFromEncodedData(data);这一行

因为我也用过`skia`, 我认为可能是缓存的问题. 毕竟你使用的是 ，静态函数带来的问题可能就是 函数申请所分配的内存地址得不到即使的释放，并且函数`DeferredFromEncodedData`也是回读取缓存的. 或许这也能解释你的图片size为什么这么大.
[static sk_sp<SkData> SkData::MakeFromFileName(const char path[])	](https://api.skia.org/classSkData.html#:~:text=static%20sk_sp%3CSkData%3E%20SkData%3A%3AMakeFromFileName,)

**Comment by AppleJ01** [comment]
不过 我之前是使用MakeFromMalloc 并且搭配 ReleaseProc 来解决超出的数据部分来去释放缓存的.

**Comment by xiaozhuai** [comment]
挺奇怪的，在skia升级版本前一直都是可以运行的。

**Comment by FrankXie05** [comment]
我今天会复现一下这个问题，并且看一看新版本更新的PR做了什么改动。 
没关系的话我就去skia那边问一问.

**Comment by FrankXie05** [comment]
我写了一个测试用例，并且将数据刘输出到了 test.bin 当中， skia的函数使用都没有问题. 
由于 我的 控制台是cmd的，所以我的输出都用了拼音，但是我尽可能的加入了注释.
我用的图片是你的那个测试图片，我在调试的时候也有一个奇怪的问题，就是图片路径. 
最后，我还是使用了绝对路径去debug了。

CMakeLists.txt和你的一样.
`main.cpp`:
[main.cpp.txt](https://github.com/xiaozhuai/vcpkg_demo/files/13578417/main.cpp.txt)


![image](https://github.com/xiaozhuai/vcpkg_demo/assets/65999885/8d9e22ba-1add-4350-ba3d-926048c2a1a2)

**Comment by FrankXie05** [comment]
我尽量都加入了 检错和对比机制.

**Comment by xiaozhuai** [comment]
<img width="457" alt="image" src="https://github.com/xiaozhuai/vcpkg_demo/assets/4773701/7e6ad3c2-5aaa-4c67-92a1-2ed5809b40c7">

@FrankXie05 这是我用你的测试代码在macOS上运行的结果。

**Comment by xiaozhuai** [comment]
![无标题](https://github.com/xiaozhuai/vcpkg_demo/assets/4773701/bd01315c-d5eb-411b-b79f-a3a1badee761)

另外我在windows上尝试运行了一下，是没有问题的。所以看起来这个问题并不是skia如何使用上的问题。

**Comment by FrankXie05** [comment]
emmm...  🫤， 那可能是skia在osx上对于图片的处理不同吧.

**Comment by FrankXie05** [comment]
忽视掉错误 的话，在osx上能够返回`DeferredFromEncodedData`的值么？

**Comment by FrankXie05** [comment]
毕竟 `getFileSize`和 `SkData::MakeFromFileName` 是不能划等号的.

**Comment by xiaozhuai** [comment]
> 忽视掉错误 的话，在osx上能够返回DeferredFromEncodedData的值么？

不能，运行到这里会直接就触发SIGBUS崩溃了

**Comment by xiaozhuai** [comment]
<img width="1288" alt="image" src="https://github.com/xiaozhuai/vcpkg_demo/assets/4773701/89f003b7-81c2-4da8-be9f-fccdbf8b3283">
这是崩溃时的调用栈

**Comment by FrankXie05** [comment]
也是，毕竟分配的内存地址和SkData获取到的完全不同.

> > 忽视掉错误 的话，在osx上能够返回DeferredFromEncodedData的值么？
> 
> 不能，运行到这里会直接就触发SIGBUS崩溃了

**Comment by xiaozhuai** [comment]
看起来是sk_sp智能指针在自增引用计数时触发的。就非常奇怪

**Comment by FrankXie05** [comment]
不会是因为太大而被释放了吧，导致悬空指针了.

**Comment by xiaozhuai** [comment]
> 不会是因为太大而被释放了吧，导致悬空指针了.

不会的，这才1.2M的图，就是解码之后的bitmap 1920x1080也才8M

**Comment by FrankXie05** [comment]
关于vcpkg那边我看了，最近的skia的更新没有设计到任何的方法修改. 只是做了简单的更新版本和清理工作.

**Comment by xiaozhuai** [comment]
> 关于vcpkg那边我看了，最近的skia的更新没有设计到任何的方法修改. 只是做了简单的更新版本和清理工作.

我也看过了，没有什么可疑的地方，有可能是上游的问题。

**Comment by FrankXie05** [comment]
还是去问问skia吧，他们应该会知道关于更多的细节.

**Comment by FrankXie05** [comment]
https://issues.skia.org/issues

**Comment by xiaozhuai** [comment]
@FrankXie05 发现一个奇怪的事情，由于我之前一直在debug环境测试的，我刚试了一下release，可以运行...

**Comment by FrankXie05** [comment]
我的理解： Release模式通常会启用更高级的优化，来减少构建时间和文件大小。而这些优化可能会影响 文件路径、变量的生命周期、函数内联的问题。
而Debug包含更多的调试信息，甚至更多的额外调试信息，而这些调试信息直接会影响内存布局的变化.

**Comment by FrankXie05** [comment]
不过，我们也不清楚skia在debug下做了什么？ 我知道的是编译器在release下更加倾向内联函数(`inline`). 🫤

**Comment by xiaozhuai** [comment]
@FrankXie05 嗯，还是回到vcpkg那边去讨论吧，看看其他人有什么线索没有。给我的感觉还是上游的问题。
